- name: update
  hosts: kluster
  tasks:
  - name: update cache
    become: yes
    ansible.builtin.apt:
      update_cache: yes

  - name: Update all packages to their latest version
    become: yes
    ansible.builtin.apt:
      name: "*"
      state: latest